# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CwcCli < Formula
  desc ""
  homepage "https://github.com/amirghedira/cwc-cli"
  version "0.1.5"

  on_macos do
    url "https://github.com/amirghedira/cwc-cli/releases/download/v0.1.5/cwc-cli_0.1.5_darwin_all.tar.gz"
    sha256 "62d2585fb2bdc129396b77a61570f5fd0f57d6d66c1cf95955705ff0378da480"

    def install
      bin.install "cwc-cli"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/amirghedira/cwc-cli/releases/download/v0.1.5/cwc-cli_0.1.5_linux_arm64.tar.gz"
      sha256 "07f9862d6d79fe2932afd6dd858050fc5a0a2acd8871da0141f136884f170e65"

      def install
        bin.install "cwc"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/amirghedira/cwc-cli/releases/download/v0.1.5/cwc-cli_0.1.5_linux_amd64.tar.gz"
      sha256 "54cf89b9b5d2df28aa4d29b0925a7c5c85fdd8d9c21d6742780a6f47b3d0b268"

      def install
        bin.install "cwc"
      end
    end
  end
end
